### ISSUE TITLE
book requirment

### ISSUE THREAD

**Issue by najeex** [NguyenDa18/DeepLearningNLP#1]
hey there. do you have Deep Learning for Natural Language Processing? if yes kindly share. thanks

**Comment by NguyenDa18** [comment]
Hi najeex. I can't share the PDF book online but I can send it to you privately. Or I can post all of the code samples onto github. Let me know which you prefer. Thanks.

**Comment by NguyenDa18** [comment]
Hi @najeex. I can add the code snippets from the book to my repo and organize my repo better, I think that is what you meant by indexing. Thanks

**Comment by NguyenDa18** [comment]
@najeex I added all the code from the book to the repository if you haven't checked it yet.
https://github.com/NguyenDa18/DeepLearningNLP/tree/master/Book_Code_Snippets

**Comment by najeex** [comment]
thanks, @NguyenDa18 it is really helpful.

**Comment by NguyenDa18** [comment]
No problem. @najeex I will add READMEs to the posted Book Code Snippets so you are able to tell what the snippets are supposed to do, and how they relate to the lesson from the book

**Comment by tuanpase05114fpt** [comment]
@NguyenDa18 anh ơi em đang tìm tài liệu về deep learning cho NLP để làm đồ án ạ, anh có thể share private cho em tài liệu pdf được không ạ? em sẽ không share online mà chỉ để dùng trong nhóm thôi ạ. em cám ơn anh 💃

**Comment by najeex** [comment]
hey @NguyenDa18 in deeplearningNPL repo some importent data file are missing without this data file code are useless for me. kindly share file and pdf najeebagra@outlook.com . and you repo really helpful for me learning NLP. thanks

**Comment by najeex** [comment]
hope you remember. I am learning NLP for a college project and your repo really helps to hands-on NLP. I realize the code is not well commented and some data file are missing. this make to hard to learning.  can you share the book with me it really helps me? if some problem you have let me know. thanks

**Comment by NguyenDa18** [comment]
Hi @najeex I did send the book to you four days ago. Perhaps check your email in the spam folder. Thanks.
![nlp_sent](https://user-images.githubusercontent.com/14105469/41926136-5cfc6664-7923-11e8-8980-fd25645f802d.PNG)

**Comment by najeex** [comment]
thanks

**Comment by najeex** [comment]
hey @NguyenDa18  you pdf file is corrupted.which send me. can not open. kindly send me uncorrupted file. thanks

**Comment by WaqasAhmad007** [comment]
Hello NguyenDa can please send me the book pdf to my email( wa28877@gmail.com) iam grateful to you. Thanks

**Comment by Ajith-Shenoy** [comment]
@najeex please help a fellow Bangalorean out and mail me the book at ajithshenoy19@gmail.com thanks.
@NguyenDa18 please send me a copy if you can
